// Generated by CoffeeScript 1.6.3
(function() {
  var Product;

  Product = (function() {
    function Product(name, price) {
      this.name = name;
      this.price = price;
    }

    Product.prototype.sale_price = function(discount) {
      return this.price * (1 - discount);
    };

    return Product;

  })();

  module.exports = Product;

}).call(this);
